// jest and vitest both provide a global `.fn()` stub factory AND `.mock()` module-level
// auto-mocking with hoisting semantics. Mocha has NEITHER built in — projects bring their own
// mocking library (most commonly sinon), whose API (`.stub()`/`.returns()`/`.resolves()`, no
// module-auto-mock/hoisting concept at all) is structurally different, not a drop-in rename.
// Emitting jest.fn()/jest.mock()-shaped guidance unconditionally for mocha asserted an API that
// doesn't exist there. Rather than invent unverified sinon-native phrasing, every jest/vitest-
// specific mock instruction block is replaced with this one honest disclaimer for any other
// JS-family runner (currently just mocha).
export function nonStandardMockApiNote(): string {
  return "This project's test runner has no standardized, autodetectable mocking API — lacuna's mock-shape guidance assumes jest's or vitest's jest.fn()/jest.mock() (or vi.fn()/vi.mock()). Mock dependencies using whatever mocking library this project already uses (e.g. sinon), matching the exact shape the source code actually calls."
}

export function buildJsCauses(mockApi: string, hasFnStyleMockApi = true): string {
  if (!hasFnStyleMockApi) return `\n- ${nonStandardMockApiNote()}`
  return `
- NEVER write require() anywhere in test files — @typescript-eslint/no-require-imports flags it everywhere, including inside test() and beforeEach() callbacks. Use ES import statements instead. To access real module values inside ${mockApi}.mock() factories, use ${mockApi}.requireActual() — it is a method on the ${mockApi} global (always in scope) and is never flagged.
- FILE STRUCTURE — strict ordering to avoid import/first ESLint errors: (1) ALL import statements at the very top; (2) ALL ${mockApi}.mock() calls below all imports; (3) test code (describe/it/beforeEach). NEVER add an import statement after any ${mockApi}.mock() call — this triggers import/first even if earlier imports exist. Plan all imports before writing any mock call.
- ${mockApi}.mock() FACTORY SCOPE — the test framework hoists ALL ${mockApi}.mock() calls before any import statement. Two consequences: (a) imported bindings (React, View, any named import) are NOT in scope — referencing them throws ReferenceError; (b) module-scope variables — EVEN mock-prefixed ones like \`const MockTabs = ${mockApi}.fn()\` — are NOT hoisted. They pass the compiler's error check, but because the factory fires during the import phase (before module-scope declarations run), they are still undefined when the factory executes. WRONG: \`const MockTabs = ${mockApi}.fn(); ${mockApi}.mock('expo-router', () => ({ Tabs: MockTabs }))\` — MockTabs is undefined at factory time. RIGHT approach — self-contained factories: define every mock function as a local variable INSIDE the factory body using ${mockApi}.fn() (a global, always in scope). Access the same instances from tests via ${mockApi}.mocked() on the static import — after hoisting, the static import resolves to the factory's mock: \`import { Tabs } from 'expo-router'; ${mockApi}.mock('expo-router', () => { const Tabs = ${mockApi}.fn(() => null); Tabs.Screen = ${mockApi}.fn(() => null); return { Tabs }; }); const mockTabs = ${mockApi}.mocked(Tabs); beforeEach(() => { mockTabs.mockImplementation(...); });\` For namespaced mocks (e.g. Tabs.Screen): assign sub-properties inside the factory, not from outside. For accessing real module internals: use ${mockApi}.requireActual() — \`${mockApi}\` is always in scope inside a factory.
- Component mocks: NEVER use React.createElement() or JSX inside a ${mockApi}.mock() factory — React is an imported binding and is not in scope when the factory runs (throws ReferenceError or "Invalid variable access" — not React Native specific, ANY imported binding fails the same way). Mock components as \`${mockApi}.fn(() => null)\` instead. If the test genuinely needs a testID or rendered text from the mock, use ${mockApi}.requireActual() to pull in React inside the factory: \`${mockApi}.fn(({ value }) => { const React = ${mockApi}.requireActual('react'); const { View } = ${mockApi}.requireActual('react-native'); return React.createElement(View, { testID: 'my-component' }); })\`.
- clearAllMocks() wipes ALL ${mockApi}.fn() implementations, including those created inside ${mockApi}.mock() factories. After the first test's afterEach, any ${mockApi}.fn() in a factory has no implementation and returns undefined — causing "Nothing was returned from render". Fix: re-apply implementations in beforeEach using ${mockApi}.mocked() — declare \`const mockFn = ${mockApi}.mocked(importedFn)\` at module scope (after the ${mockApi}.mock() call), then call mockFn.mockImplementation(...) in beforeEach. Note: clearAllMocks() does NOT delete object properties (e.g. Tabs.Screen still exists after clear — only its implementation is gone).
- ${mockApi}.mock() paths are relative to the TEST FILE, not the source file. Count directories from the test file's location, not the source file's.
- Missing mock is the silent killer: if expect(mockFn).toHaveBeenCalled() fails but the code path is clearly reached, the mock declaration is missing or uses the wrong path. The real implementation ran instead.
- Response envelope mismatch (silent empty state): if a hook guards \`if (res.success)\` or destructures \`{ success, data }\`, mocking with a raw array means .success is undefined and state is never populated — silently. Trace each call site individually — different clients in the same hook often have different shapes (one returns \`{ data: [] }\`, another \`{ success, data: { items: [] } }\` with nested access). Never assume a uniform envelope across the whole hook.
- Barrel file mock miss: mocking a barrel/index file (${mockApi}.mock('../components')) will NOT intercept imports of the direct file ('../components/Foo'). Mock the specific module the source actually imports.`
}
